voters = [
    'Архитектонски факултет',
    'Биолошки факултет',
    'Ветеринарска медицина',
    'Географски факултет',
    'Грађевински факултет',
    'Економски факултет',
    'Електротехнички факултет',
    'Математички факултет',
    'Машински факултет',
    'Медицински факултет',
    'Пољопривредни факултет',
    'Правни факултет',
    'Православни богословски факултет',
    'Рударско-геолошки факултет',
    'Саобраћајни факултет',
    'Стоматолошки факултет',
    'Технички факултет у Бору',
    'Технолошко-металуршки факултет',
    'Факултет безбедности',
    'Факултет драмских уметности',
    'Факултет за образовање учитеља и васпитача',
    'Факултет за специјалну едукацију и рехабилитацију',
    'Факултет за физичку хемију',
    'Факултет музичке уметности',
    'Факултет организационих наука',
    'Факултет политицких наука',
    'Факултет примењених уметности',
    'Факултет спорта и физичког васпитања',
    'Фармацеутски факултет',
    'Физички факултет',
    'Филозофски факултет',
    'Филолоски факултет',
    'Хемијски факултет',
    'Шумарски факултет',
]
