voters = [
    # UBG
    { name = 'Архитектонски факултет', short = 'АРХ', ubg = true },
    { name = 'Биолошки факултет', short = 'БИОФ', ubg = true },
    { name = 'Факултет ветеринарске медицине', short = 'ФВМ', ubg = true },
    { name = 'Географски факултет', short = 'ГЕФ', ubg = true },
    { name = 'Грађевински факултет', short = 'ГРФ', ubg = true },
    { name = 'Економски факултет', short = 'ЕКОФ', ubg = true },
    { name = 'Електротехнички факултет', short = 'ЕТФ', ubg = true },
    { name = 'Математички факултет', short = 'МАТФ', ubg = true },
    { name = 'Машински факултет', short = 'МФ', ubg = true },
    { name = 'Медицински факултет', short = 'МФУБ', ubg = true },
    { name = 'Пољопривредни факултет', short = 'АГРИФ', ubg = true },
    { name = 'Правни факултет', ubg = true },
    { name = 'Православни богословски факултет', short = 'ПБФ', ubg = true },
    { name = 'Рударско-геолошки факултет', short = 'РГФ', ubg = true },
    { name = 'Саобраћајни факултет', short = 'СФ', ubg = true },
    { name = 'Стоматолошки факултет', short = 'СТОМФ', ubg = true },
    { name = 'Технички факултет у Бору', short = 'ТФБОР', ubg = true },
    { name = 'Технолошко-металуршки факултет', short = 'ТМФ', ubg = true },
    { name = 'Факултет безбедности', short = 'ФБ', ubg = true },
    { name = 'Факултет драмских уметности', short = 'ФДУ', ubg = true },
    { name = 'Факултет за образовање учитеља и васпитача', short = 'УФ', ubg = true },
    { name = 'Факултет за специјалну едукацију и рехабилитацију', short = 'ФАСПЕР', ubg = true },
    { name = 'Факултет за физичку хемију', short = 'ФФХ', ubg = true },
    { name = 'Факултет музичке уметности', short = 'ФМУ', ubg = true },
    { name = 'Факултет организационих наука', short = 'ФОН', ubg = true },
    { name = 'Факултет политичких наука', short = 'ФПН', ubg = true },
    { name = 'Факултет примењених уметности', short = 'ФПУ', ubg = true },
    { name = 'Факултет спорта и физичког васпитања', short = 'ДИФ', ubg = true },
    { name = 'Фармацеутски факултет', ubg = true },
    { name = 'Физички факултет', short = 'ФИЗФ', ubg = true },
    { name = 'Филозофски факултет', short = 'Ф', ubg = true },
    { name = 'Филолошки факултет', short = 'ФИЛ', ubg = true },
    { name = 'Хемијски факултет', short = 'ХФ', ubg = true },
    { name = 'Шумарски факултет', short = 'ШФБ', ubg = true },

    # Non-UBG
    { name = 'Академија Уметности', short = 'АУБГ'},
    { name = 'Висока туристичка школа', short = 'ВТШ'},
    { name = 'Факултет за медије и комуникације', short = 'ФМК'},
    { name = 'Факултет ликовних уметности', short = 'ФЛУ'},
    { name = 'Београдска академија пословних и уметничких струковних студија', short = 'БАПУСС'},
    { name = 'Факултет савремених уметности', short = 'ФСУ'},
    { name = 'Универзитет Метрополитан', short = ''},
    { name = 'Висока школа електротехнике и рачунарства', short = 'ВИШЕР'},
    'Политехника',
]
